name: PR Workflow

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update README
      run: |
        echo "This is an automated update to the README file." >> README.md
    
