name: SEDHU_WORKFLOW
on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest
    steps:    
      
      - name: Validation Stage
        uses: CanarysPlayground/apicall-composite-action@master
        with:
          Token: ${{secrets.API_TOKEN}}
          Header: ${{secrets.HEADER}}
          RequestBody: ${{secrets.REQUESTBODY}}
          ExpectedOutput: ${{secrets.EXPECTEDOUTPUT}}
    
  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - uses: actions/checkout@v2
